version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8070:8070"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5430:5432"
    # todo add volume here
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s